plugins:
  - rubocop-performance
  - rubocop-packaging
  - rubocop-rake
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude: 
    - spec/*.rb
    - lib/*_pb.rb # generated proto files
    - vendor/**/*
    - gemfiles/vendor/bundle/**/*

# Disabling until TravelTime Rubygems account is MFA-protected.
Gemspec/RequireMFA:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Max: 10

Metrics/ParameterLists:
  Enabled: false
