require:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.7
  NewCops: enable

# Disabling until TravelTime Rubygems account is MFA-protected.
Gemspec/RequireMFA:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/Rails/HaveHttpStatus:
  Enabled: false
