# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GeohashFastResponse.proto

require 'google/protobuf'


descriptor_data = "\n\x19GeohashFastResponse.proto\x12*com.igeolise.traveltime.rabbitmq.responses\"\xca\x01\n\x13GeohashFastResponse\x12T\n\x05\x63\x65lls\x18\x01 \x01(\x0b\x32\x45.com.igeolise.traveltime.rabbitmq.responses.GeohashFastResponse.Cells\x1a]\n\x05\x43\x65lls\x12\x0b\n\x03ids\x18\x01 \x03(\t\x12\x16\n\x0eminTravelTimes\x18\x02 \x03(\x11\x12\x16\n\x0emaxTravelTimes\x18\x03 \x03(\x11\x12\x17\n\x0fmeanTravelTimes\x18\x04 \x03(\x11\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Com
  module Igeolise
    module Traveltime
      module Rabbitmq
        module Responses
          GeohashFastResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.igeolise.traveltime.rabbitmq.responses.GeohashFastResponse").msgclass
          GeohashFastResponse::Cells = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.igeolise.traveltime.rabbitmq.responses.GeohashFastResponse.Cells").msgclass
        end
      end
    end
  end
end
