# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: H3FastRequest.proto

require 'google/protobuf'

require 'RequestsCommon_pb'


descriptor_data = "\n\x13H3FastRequest.proto\x12)com.igeolise.traveltime.rabbitmq.requests\x1a\x14RequestsCommon.proto\"\xa9\x08\n\rH3FastRequest\x12\\\n\x10oneToManyRequest\x18\x01 \x01(\x0b\x32\x42.com.igeolise.traveltime.rabbitmq.requests.H3FastRequest.OneToMany\x12\\\n\x10manyToOneRequest\x18\x02 \x01(\x0b\x32\x42.com.igeolise.traveltime.rabbitmq.requests.H3FastRequest.ManyToOne\x1a\xad\x03\n\tOneToMany\x12L\n\x11\x64\x65partureLocation\x18\x01 \x01(\x0b\x32\x31.com.igeolise.traveltime.rabbitmq.requests.Coords\x12Q\n\x0etransportation\x18\x02 \x01(\x0b\x32\x39.com.igeolise.traveltime.rabbitmq.requests.Transportation\x12P\n\x11\x61rrivalTimePeriod\x18\x03 \x01(\x0e\x32\x35.com.igeolise.traveltime.rabbitmq.requests.TimePeriod\x12\x12\n\ntravelTime\x18\x04 \x01(\x11\x12\x12\n\nresolution\x18\x05 \x01(\r\x12O\n\nproperties\x18\x06 \x03(\x0e\x32;.com.igeolise.traveltime.rabbitmq.requests.CellPropertyType\x12\x1e\n\x11removeWaterBodies\x18\x07 \x01(\x08H\x00\x88\x01\x01\x42\x14\n\x12_removeWaterBodies\x1a\xab\x03\n\tManyToOne\x12J\n\x0f\x61rrivalLocation\x18\x01 \x01(\x0b\x32\x31.com.igeolise.traveltime.rabbitmq.requests.Coords\x12Q\n\x0etransportation\x18\x02 \x01(\x0b\x32\x39.com.igeolise.traveltime.rabbitmq.requests.Transportation\x12P\n\x11\x61rrivalTimePeriod\x18\x03 \x01(\x0e\x32\x35.com.igeolise.traveltime.rabbitmq.requests.TimePeriod\x12\x12\n\ntravelTime\x18\x04 \x01(\x11\x12\x12\n\nresolution\x18\x05 \x01(\r\x12O\n\nproperties\x18\x06 \x03(\x0e\x32;.com.igeolise.traveltime.rabbitmq.requests.CellPropertyType\x12\x1e\n\x11removeWaterBodies\x18\x07 \x01(\x08H\x00\x88\x01\x01\x42\x14\n\x12_removeWaterBodiesb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
    ["com.igeolise.traveltime.rabbitmq.requests.Coords", "RequestsCommon.proto"],
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Com
  module Igeolise
    module Traveltime
      module Rabbitmq
        module Requests
          H3FastRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.igeolise.traveltime.rabbitmq.requests.H3FastRequest").msgclass
          H3FastRequest::OneToMany = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.igeolise.traveltime.rabbitmq.requests.H3FastRequest.OneToMany").msgclass
          H3FastRequest::ManyToOne = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.igeolise.traveltime.rabbitmq.requests.H3FastRequest.ManyToOne").msgclass
        end
      end
    end
  end
end
