# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RequestsCommon.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("RequestsCommon.proto", :syntax => :proto3) do
    add_message "com.igeolise.traveltime.rabbitmq.requests.Coords" do
      optional :lat, :float, 1
      optional :lng, :float, 2
    end
    add_message "com.igeolise.traveltime.rabbitmq.requests.Transportation" do
      optional :type, :enum, 1, "com.igeolise.traveltime.rabbitmq.requests.TransportationType"
    end
    add_enum "com.igeolise.traveltime.rabbitmq.requests.TransportationType" do
      value :PUBLIC_TRANSPORT, 0
      value :DRIVING, 1
      value :DRIVING_AND_PUBLIC_TRANSPORT, 2
      value :DRIVING_AND_FERRY, 3
      value :WALKING, 4
      value :WALKING_AND_FERRY, 7
      value :CYCLING, 5
      value :CYCLING_AND_FERRY, 6
    end
    add_enum "com.igeolise.traveltime.rabbitmq.requests.TimePeriod" do
      value :WEEKDAY_MORNING, 0
    end
  end
end

module Com
  module Igeolise
    module Traveltime
      module Rabbitmq
        module Requests
          Coords = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.igeolise.traveltime.rabbitmq.requests.Coords").msgclass
          Transportation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.igeolise.traveltime.rabbitmq.requests.Transportation").msgclass
          TransportationType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.igeolise.traveltime.rabbitmq.requests.TransportationType").enummodule
          TimePeriod = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.igeolise.traveltime.rabbitmq.requests.TimePeriod").enummodule
        end
      end
    end
  end
end
