# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RequestsCommon.proto

require 'google/protobuf'


descriptor_data = "\n\x14RequestsCommon.proto\x12)com.igeolise.traveltime.rabbitmq.requests\"\"\n\x06\x43oords\x12\x0b\n\x03lat\x18\x01 \x01(\x02\x12\x0b\n\x03lng\x18\x02 \x01(\x02\"\xc6\x02\n\x0eTransportation\x12K\n\x04type\x18\x01 \x01(\x0e\x32=.com.igeolise.traveltime.rabbitmq.requests.TransportationType\x12\\\n\x0fpublicTransport\x18\x02 \x01(\x0b\x32\x41.com.igeolise.traveltime.rabbitmq.requests.PublicTransportDetailsH\x00\x12p\n\x19\x64rivingAndPublicTransport\x18\x03 \x01(\x0b\x32K.com.igeolise.traveltime.rabbitmq.requests.DrivingAndPublicTransportDetailsH\x00\x42\x17\n\x15transportationDetails\"y\n\x16PublicTransportDetails\x12_\n\x14walkingTimeToStation\x18\x01 \x01(\x0b\x32\x41.com.igeolise.traveltime.rabbitmq.requests.OptionalPositiveUInt32\"\xbf\x02\n DrivingAndPublicTransportDetails\x12_\n\x14walkingTimeToStation\x18\x01 \x01(\x0b\x32\x41.com.igeolise.traveltime.rabbitmq.requests.OptionalPositiveUInt32\x12_\n\x14\x64rivingTimeToStation\x18\x02 \x01(\x0b\x32\x41.com.igeolise.traveltime.rabbitmq.requests.OptionalPositiveUInt32\x12Y\n\x0bparkingTime\x18\x03 \x01(\x0b\x32\x44.com.igeolise.traveltime.rabbitmq.requests.OptionalNonNegativeUInt32\"\'\n\x16OptionalPositiveUInt32\x12\r\n\x05value\x18\x01 \x01(\r\"*\n\x19OptionalNonNegativeUInt32\x12\r\n\x05value\x18\x01 \x01(\r*\xb8\x01\n\x12TransportationType\x12\x14\n\x10PUBLIC_TRANSPORT\x10\x00\x12\x0b\n\x07\x44RIVING\x10\x01\x12 \n\x1c\x44RIVING_AND_PUBLIC_TRANSPORT\x10\x02\x12\x15\n\x11\x44RIVING_AND_FERRY\x10\x03\x12\x0b\n\x07WALKING\x10\x04\x12\x15\n\x11WALKING_AND_FERRY\x10\x07\x12\x0b\n\x07\x43YCLING\x10\x05\x12\x15\n\x11\x43YCLING_AND_FERRY\x10\x06*!\n\nTimePeriod\x12\x13\n\x0fWEEKDAY_MORNING\x10\x00*.\n\x10\x43\x65llPropertyType\x12\x08\n\x04MEAN\x10\x00\x12\x07\n\x03MIN\x10\x01\x12\x07\n\x03MAX\x10\x02\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Com
  module Igeolise
    module Traveltime
      module Rabbitmq
        module Requests
          Coords = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.igeolise.traveltime.rabbitmq.requests.Coords").msgclass
          Transportation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.igeolise.traveltime.rabbitmq.requests.Transportation").msgclass
          PublicTransportDetails = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.igeolise.traveltime.rabbitmq.requests.PublicTransportDetails").msgclass
          DrivingAndPublicTransportDetails = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.igeolise.traveltime.rabbitmq.requests.DrivingAndPublicTransportDetails").msgclass
          OptionalPositiveUInt32 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.igeolise.traveltime.rabbitmq.requests.OptionalPositiveUInt32").msgclass
          OptionalNonNegativeUInt32 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.igeolise.traveltime.rabbitmq.requests.OptionalNonNegativeUInt32").msgclass
          TransportationType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.igeolise.traveltime.rabbitmq.requests.TransportationType").enummodule
          TimePeriod = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.igeolise.traveltime.rabbitmq.requests.TimePeriod").enummodule
          CellPropertyType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.igeolise.traveltime.rabbitmq.requests.CellPropertyType").enummodule
        end
      end
    end
  end
end
