# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TimeFilterFastResponse.proto

require 'google/protobuf'


descriptor_data = "\n\x1cTimeFilterFastResponse.proto\x12*com.igeolise.traveltime.rabbitmq.responses\"\x84\x08\n\x16TimeFilterFastResponse\x12[\n\x05\x65rror\x18\x01 \x01(\x0b\x32H.com.igeolise.traveltime.rabbitmq.responses.TimeFilterFastResponse.ErrorB\x02\x18\x01\x12\x61\n\nproperties\x18\x02 \x01(\x0b\x32M.com.igeolise.traveltime.rabbitmq.responses.TimeFilterFastResponse.Properties\x1aJ\n\nProperties\x12\x13\n\x0btravelTimes\x18\x01 \x03(\x11\x12\x14\n\x0cmonthlyFares\x18\x02 \x03(\x05\x12\x11\n\tdistances\x18\x03 \x03(\x05\x1a\x63\n\x05\x45rror\x12Z\n\x04type\x18\x01 \x01(\x0e\x32L.com.igeolise.traveltime.rabbitmq.responses.TimeFilterFastResponse.ErrorType\"\xf8\x04\n\tErrorType\x12\x0f\n\x07UNKNOWN\x10\x00\x1a\x02\x08\x01\x12$\n\x1cONE_TO_MANY_MUST_NOT_BE_NULL\x10\x01\x1a\x02\x08\x01\x12\x1f\n\x17SOURCE_MUST_NOT_BE_NULL\x10\x02\x1a\x02\x08\x01\x12\'\n\x1fTRANSPORTATION_MUST_NOT_BE_NULL\x10\x03\x1a\x02\x08\x01\x12\x1e\n\x16SOURCE_NOT_IN_GEOMETRY\x10\x04\x1a\x02\x08\x01\x12(\n UNRECOGNIZED_TRANSPORTATION_MODE\x10\x05\x1a\x02\x08\x01\x12!\n\x19TRAVEL_TIME_LIMIT_TOO_LOW\x10\x06\x1a\x02\x08\x01\x12\"\n\x1aTRAVEL_TIME_LIMIT_TOO_HIGH\x10\x07\x1a\x02\x08\x01\x12\x1d\n\x15\x41UTH_ERROR_NO_USER_ID\x10\x08\x1a\x02\x08\x01\x12\x32\n*SERVICE_MISMATCH_WRONG_TRANSPORTATION_MODE\x10\t\x1a\x02\x08\x01\x12\x1b\n\x13SOURCE_OUT_OF_REACH\x10\n\x1a\x02\x08\x01\x12\x33\n+INTERLEAVED_DELTAS_INVALID_COORDINATE_PAIRS\x10\x0b\x1a\x02\x08\x01\x12\'\n\x1f\x44ISTANCE_PROPERTY_NOT_SUPPORTED\x10\x0c\x1a\x02\x08\x01\x12\x37\n/BOTH_MANY_TO_ONE_AND_ONE_TO_MANY_CANNOT_BE_SENT\x10\r\x1a\x02\x08\x01\x12\x33\n+ONE_TO_MANY_OR_MANY_TO_ONE_MUST_NOT_BE_NULL\x10\x0e\x1a\x02\x08\x01\x12\x1d\n\x15INVALID_PROTO_REQUEST\x10\x0f\x1a\x02\x08\x01\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Com
  module Igeolise
    module Traveltime
      module Rabbitmq
        module Responses
          TimeFilterFastResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.igeolise.traveltime.rabbitmq.responses.TimeFilterFastResponse").msgclass
          TimeFilterFastResponse::Properties = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.igeolise.traveltime.rabbitmq.responses.TimeFilterFastResponse.Properties").msgclass
          TimeFilterFastResponse::Error = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.igeolise.traveltime.rabbitmq.responses.TimeFilterFastResponse.Error").msgclass
          TimeFilterFastResponse::ErrorType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.igeolise.traveltime.rabbitmq.responses.TimeFilterFastResponse.ErrorType").enummodule
        end
      end
    end
  end
end
