# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TimeFilterFastResponse.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("TimeFilterFastResponse.proto", :syntax => :proto3) do
    add_message "com.igeolise.traveltime.rabbitmq.responses.TimeFilterFastResponse" do
      optional :error, :message, 1, "com.igeolise.traveltime.rabbitmq.responses.TimeFilterFastResponse.Error"
      optional :properties, :message, 2, "com.igeolise.traveltime.rabbitmq.responses.TimeFilterFastResponse.Properties"
    end
    add_message "com.igeolise.traveltime.rabbitmq.responses.TimeFilterFastResponse.Properties" do
      repeated :travelTimes, :sint32, 1
      repeated :monthlyFares, :int32, 2
      repeated :distances, :int32, 3
    end
    add_message "com.igeolise.traveltime.rabbitmq.responses.TimeFilterFastResponse.Error" do
      optional :type, :enum, 1, "com.igeolise.traveltime.rabbitmq.responses.TimeFilterFastResponse.ErrorType"
    end
    add_enum "com.igeolise.traveltime.rabbitmq.responses.TimeFilterFastResponse.ErrorType" do
      value :UNKNOWN, 0
      value :ONE_TO_MANY_MUST_NOT_BE_NULL, 1
      value :SOURCE_MUST_NOT_BE_NULL, 2
      value :TRANSPORTATION_MUST_NOT_BE_NULL, 3
      value :SOURCE_NOT_IN_GEOMETRY, 4
      value :UNRECOGNIZED_TRANSPORTATION_MODE, 5
      value :TRAVEL_TIME_LIMIT_TOO_LOW, 6
      value :TRAVEL_TIME_LIMIT_TOO_HIGH, 7
      value :AUTH_ERROR_NO_USER_ID, 8
      value :SERVICE_MISMATCH_WRONG_TRANSPORTATION_MODE, 9
      value :SOURCE_OUT_OF_REACH, 10
      value :INTERLEAVED_DELTAS_INVALID_COORDINATE_PAIRS, 11
      value :DISTANCE_PROPERTY_NOT_SUPPORTED, 12
    end
  end
end

module Com
  module Igeolise
    module Traveltime
      module Rabbitmq
        module Responses
          TimeFilterFastResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.igeolise.traveltime.rabbitmq.responses.TimeFilterFastResponse").msgclass
          TimeFilterFastResponse::Properties = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.igeolise.traveltime.rabbitmq.responses.TimeFilterFastResponse.Properties").msgclass
          TimeFilterFastResponse::Error = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.igeolise.traveltime.rabbitmq.responses.TimeFilterFastResponse.Error").msgclass
          TimeFilterFastResponse::ErrorType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.igeolise.traveltime.rabbitmq.responses.TimeFilterFastResponse.ErrorType").enummodule
        end
      end
    end
  end
end
