# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TimeFilterFastRequest.proto

require 'google/protobuf'

require_relative 'RequestsCommon_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("TimeFilterFastRequest.proto", :syntax => :proto3) do
    add_message "com.igeolise.traveltime.rabbitmq.requests.TimeFilterFastRequest" do
      optional :oneToManyRequest, :message, 1, "com.igeolise.traveltime.rabbitmq.requests.TimeFilterFastRequest.OneToMany"
    end
    add_message "com.igeolise.traveltime.rabbitmq.requests.TimeFilterFastRequest.OneToMany" do
      optional :departureLocation, :message, 1, "com.igeolise.traveltime.rabbitmq.requests.Coords"
      repeated :locationDeltas, :sint32, 2
      optional :transportation, :message, 3, "com.igeolise.traveltime.rabbitmq.requests.Transportation"
      optional :arrivalTimePeriod, :enum, 4, "com.igeolise.traveltime.rabbitmq.requests.TimePeriod"
      optional :travelTime, :sint32, 5
      repeated :properties, :enum, 6, "com.igeolise.traveltime.rabbitmq.requests.TimeFilterFastRequest.Property"
    end
    add_enum "com.igeolise.traveltime.rabbitmq.requests.TimeFilterFastRequest.Property" do
      value :FARES, 0
      value :DISTANCES, 1
    end
  end
end

module Com
  module Igeolise
    module Traveltime
      module Rabbitmq
        module Requests
          TimeFilterFastRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.igeolise.traveltime.rabbitmq.requests.TimeFilterFastRequest").msgclass
          TimeFilterFastRequest::OneToMany = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.igeolise.traveltime.rabbitmq.requests.TimeFilterFastRequest.OneToMany").msgclass
          TimeFilterFastRequest::Property = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.igeolise.traveltime.rabbitmq.requests.TimeFilterFastRequest.Property").enummodule
        end
      end
    end
  end
end
